# Project information
site_name: Technical Notes
site_description: A Material Design theme for MkDocs
site_author: Lewis James Martin
site_url: https://ljmartin.github.io/technical-notes/

# Repository
repo_name: ljmartin/technical_notes
repo_url: https://github.com/ljmartin/technical_notes

# Copyright
copyright: Copyright &copy; 2016 - 2020 Martin Donath

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: red
    accent: orange
  font:
    text: Barlow
    code: Inconsolata

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ljmartin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lewischewis
#    - icon: fontawesome/brands/linkedin
#      link: https://linkedin.com/in/squidfunk

# Google Analytics
#google_analytics:
#  - UA-XXXXXXXX-X
#  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'index.md'
  - 'Stats':
    - 'Random variables': 'stats/random-variables.md'
    - 'Estimators': 'stats/estimators.md'
    - 'Estimators for autocorrelated data': 'stats/estimators-autocorrelated.md'


